threadsafe: false
runtime: python27
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: favicon.ico

- url: /updateData.*
  script: cron/updateData.py
  login: admin

- url: /_ah/api.*
  script: webservice.app

- url: /.*
  script: main.app